server:
  port: 8081

dev:
  dev: abc
spring:
  datasource:
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pipro
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
      additional-paths: /src/main/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  file:
    name: pipro.log
    path: classpath:/
  level:
    pinfo: INFO
    pdebug : DEBUG
    perror: ERROR
  group:
    pdebug:
      - net._1di.piproserver.mapper
      - net._1di.piproserver
    pinfo:
      - net._1di.piproserver.component
      - net._1di.piproserver.controller.api
      - net._1di.piproserver.controller.system
